### ISSUE TITLE
Alignment for the cells formatting doesn't work

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#3]
If there is an alignment setting in Cell formatting it doesn't consider in LPT.
Here is an example:
How it looks like in DSW:
<img width="426" alt="2017-01-08 11 41 04" src="https://cloud.githubusercontent.com/assets/2781759/21747110/5f98cb5a-d597-11e6-8d32-5b16619fe61d.png">

And how it should work:
![Uploading Скриншот 2017-01-08 11.39.45.png…]()

@eduard93 Do we provide this alignment info in MDX2JSON?

**Comment by evshvarov** [comment]
Testcase: http://146.185.143.59/dsw/index.html#/d/test/Pivot%20Alignment%20Format%20Issue.dashboard?ns=SAMPLES

**Comment by nikitaeverywhere** [comment]
I see the problem is resolved [here](http://146.185.143.59/dsw/index.html#!/d/test/Pivot%20Alignment%20Format%20Issue.dashboard#%2Fd%2Ftest%2FPivot%20Alignment%20Format%20Issue.dashboard%3Fns=SAMPLES). Does it? Was it MDX2JSON issue?

Please close the issue once confirmed to be resolved.

**Comment by evshvarov** [comment]
Yes, it seems it works now.
