### ISSUE TITLE
LPT calculates uses different formulas for row totals

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#4]

**Comment by evshvarov** [comment]
Fore revenue it sums the value, but for count it sums the amount of rows.
<img width="459" alt="2017-02-12 11 24 56" src="https://cloud.githubusercontent.com/assets/2781759/22863903/ffd7a4b2-f115-11e6-8d33-7ef7f0da1734.png">
Testcase:
http://146.185.143.59/dsw/index.html#!/d/test/LPT4.dashboard#%2F%3Fns=SAMPLES

**Comment by nikitaeverywhere** [comment]
LPT implements `COUNT` aggregate as [a count of non-empty rows displayed](https://github.com/intersystems-ru/LightPivotTable/blob/dea08fb579c161dd24f1f6f247cf91c9264eb123/source/js/DataController.js#L324). Should this turn into `SUM` of values? If it is, how is it different from `SUM` aggregate?

**Comment by evshvarov** [comment]
For Total it should be always SUM

**Comment by nikitaeverywhere** [comment]
Done https://github.com/intersystems-ru/LightPivotTable/releases/tag/1.8.13 (I noticed that v1.8.13 was published in releases before while it should have been v1.8.12. So I've updated description and attached zip archive)

**Comment by nikitaeverywhere** [comment]
However, I don't like [this fix](https://github.com/intersystems-ru/LightPivotTable/commit/b8f94d5e53ccd4835febf633ab68c77ba824e995#diff-67a87257d1abee842f92d7091fcd0425): I think it will bubble up shortly somewhere.
