### ISSUE TITLE
Perform drillthrough in pivot only if Showlisting control is presented on the widget in DSZ

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#5]
Test case:
http://146.185.143.59/dsw/index.html#!/d/test/CURRVALUEandVALUELIST.dashboard#%2F%3Fns=SAMPLES

**Comment by nikitaeverywhere** [comment]
There is no pivot table there:
![2017-02-13_144008](https://cloud.githubusercontent.com/assets/4989256/22883756/5d8b2a90-f1fa-11e6-9293-296c319343dc.png)
Is it pivot-table related issue?

**Comment by evshvarov** [comment]
Switch to the pivot view (top-right corner)

**Comment by nikitaeverywhere** [comment]
Thanks! Did you mean this option?
![2017-02-13_151041](https://cloud.githubusercontent.com/assets/4989256/22884641/ad35e61c-f1fe-11e6-9da7-93f03efa2f2e.png)

**Comment by evshvarov** [comment]
No.
Showlisting control.
This feature shows drill down/up buttons.

**Comment by nikitaeverywhere** [comment]
Could you please show where this option is? Because your description is 100% description of the control on the screenshot I have mentioned above.

**Comment by evshvarov** [comment]
Same dash:
http://146.185.143.59/dsw/index.html#!/d/test/CURRVALUEandVALUELIST.dashboard#%2F%3Fns=SAMPLES
Widget Show Listing

**Comment by nikitaeverywhere** [comment]
Any progress on Daimor's pull request?

**Comment by nikitaeverywhere** [comment]
Closed due to no response. Looks like Daimor's PR fixed the issue.
