### ISSUE TITLE
How to copy in clipboard the cell value in pivot?

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/LightPivotTable#9]
Sometimes you need to copy just the value from cell in clipboard.
Haven't found the way to do that. Possibly via context menu?
@gnibeda Anton? @ZitRos Nikita?

**Comment by evshvarov** [comment]
And I'm not speaking about listing - copy to clipboard from listings works OK.

**Comment by nikitaeverywhere** [comment]
That's a bit tricky, but what I usually do, is:

1. Start selecting text inside cell but do not release left mouse button.
2. When you selected the text you need, press Ctrl + C, still pressing the button.
3. Now you're done, release the mouse button and drill!

On mobile devices long press menu works just fine.

**Comment by nikitaeverywhere** [comment]
@evshvarov, does this solves the problem? May this issue be closed?

**Comment by evshvarov** [comment]
@ZitRos No, that doesn't work. "Start selecting" doesn't work for me. Nothing is being selected from the cell in a pivot.

**Comment by nikitaeverywhere** [comment]
Oh, that worked in the past... @gnibeda, should I apply styles for the text in cell to be selectable, or the better option would be to add "Copy" to the right-click menu in DSW? Thanks!

**Comment by nikitaeverywhere** [comment]
Selector `noselect` in DSW overwrites LPT selection capabilities:

![image](https://user-images.githubusercontent.com/4989256/37568466-2836787c-2ade-11e8-942b-63f3ead432c7.png)

Should be implemented in one of the following ways:

+ DSW's context menu + copy option
+ Remove `noselect` (or enable selection inside LPT element)

**Comment by gnibeda** [comment]
fixed
